//
// Created by Kenneth Dow on 2/2/22.
//

#ifndef SEQUENCEALL_WIFIERRORCODES_H
#define SEQUENCEALL_WIFIERRORCODES_H

typedef enum {

    INIT_STA_SUCCESS = 0,
    INIT_STA_NO_CREDENTIALS_STORED = 1,
    INIT_STA_ERROR = 2,

    INIT_AP_SUCCESS = 3,
    INIT_AP_NO_CREDENTIALS_STORED = 4,
    INIT_AP_ERROR = 5,

    MDNS_COULD_NOT_ADD_SERVICE = 6,

    COULD_NOT_SET_LOCAL_HOSTNAME = 7,

    INIT_WEBSERVER_ERROR = 11,

    INIT_WIFI_SERVICE_SUCCESS = 12
} WifiErrorCode;
#endif //SEQUENCEALL_WIFIERRORCODES_H
