//
// Created by Kenneth Dow on 2/2/22.
//

#ifndef SEQUENCEALL_WIFIERRORCODES_H
#define SEQUENCEALL_WIFIERRORCODES_H

typedef enum {
    INIT_AP_SUCCESS = 2,
    INIT_AP_NO_CREDENTIALS_STORED = 3,
    INIT_AP_ERROR = 4,

    MDNS_COULD_NOT_ADD_SERVICE = 6,

    COULD_NOT_SET_LOCAL_HOSTNAME = 7,

    INIT_WEBSERVER_ERROR = 11,

    INIT_WIFI_SERVICE_SUCCESS = 12
} WifiErrorCode;
#endif //SEQUENCEALL_WIFIERRORCODES_H
